# Generated by Django 5.1.4 on 2025-03-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('global_score_home', models.PositiveSmallIntegerField(default=0)),
                ('global_score_away', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_status_home', models.BooleanField(default=False)),
                ('validation_status_away', models.BooleanField(default=False)),
                ('validation_status_superadmin', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('home_points', models.PositiveSmallIntegerField(default=0)),
                ('away_points', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_sets', to='teams.player')),
                ('home_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_sets', to='teams.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sets', to='matches.match')),
            ],
        ),
    ]
