# Generated by Django 5.1.4 on 2025-09-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EQUIPES", "EQUIPES"),
                            ("FEMININES", "FEMININES"),
                            ("MASCULINS", "MASCULINS"),
                            ("DOUBLES_MASCULINS", "DOUBLES MASCULINS"),
                            ("DOUBLES_MASCULIN_FEMININ", "DOUBLES MASCULIN-FEMININ"),
                            ("JEUNES", "JEUNES"),
                            ("DOUBLES_MASCULIN_JEUNE", "DOUBLES MASCULIN-JEUNE"),
                            ("DOUBLES_FEMININ_JEUNE", "DOUBLES FEMININ-JEUNE"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sets_won", models.PositiveIntegerField(default=0)),
                ("sets_lost", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "category")},
            },
        ),
    ]
